# Numpy

In [77]:
import numpy as np
np.__version__

'1.23.4'

In [ ]:
john = [ 10, 8, 6, 7]
x = numpy.array(john)

In [ ]:
john + 1

In [ ]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8]]
X = np.array(scores)
X

In [ ]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8]]
X = numpy.array(scores)
X

In [ ]:
import numpy as np

numpy.__version__

In [ ]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8]]
X = np.array(scores)
X

In [ ]:
X.shape

In [ ]:
X.dtype

In [ ]:
type((4,)), type((4))

In [2]:
import numpy as np

np.__version__

'1.23.4'

In [3]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8],
         [9, 10, 11, 12],
         [13, 14, 15, 16]]
X = np.array(scores)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
import numpy

numpy.__version__

'1.23.4'

In [6]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8],
         [9, 10, 11, 12],
         [13, 14, 15, 16]]
X = numpy.array(scores)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
X.shape

(4, 4)

In [11]:
scores = [[0, 1, 2, 3], 
         [4, 5, 6, 7],
         [8, 9, 10, 11],
         [12, 13, 14, 15]]
X = numpy.array(scores)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
X.shape

(2, 4, 2)

In [22]:
X = numpy.array([[4, 5, 6], 
                [8, 9, 0]])

X

array([[4, 5, 6],
       [8, 9, 0]])

In [23]:
X[-1]

array([8, 9, 0])

In [27]:
X[0, [1, 2]]

array([5, 6])

In [31]:
# fancy indexing
X[0, [1, 2]]

array([5, 6])

In [32]:
X[0, 1:]

array([5, 6])

In [34]:
# boolean indexing

X = numpy.array([1, 2, 3, 4, 5])
idx = [False, True, False, True, False,]
X[idx]

array([2, 4])

In [35]:
X = np.array([1, 5, 3, 7, 6])

X > 6

array([False, False, False,  True, False])

In [36]:
X < 5

array([ True, False,  True, False, False])

In [37]:
X = np.array([1, 5, 3, 7, 6])

idx = X > 6
X[idx]

array([7])

In [38]:
X = np.array([1, 5, 3, 7, 6])

idx = X < 5
X[idx]

array([1, 3])

In [42]:
X = numpy.array([[1, 2, 3], 
             [3, 4, 5]])
X

array([[1, 2, 3],
       [3, 4, 5]])

In [43]:
numpy.sum(X)

18

In [48]:
numpy.sum(X, axis=1)

array([ 6, 12])

In [49]:
numpy.mean(X)

3.0

In [50]:
numpy.mean(X, axis=0)

array([2., 3., 4.])

In [51]:
numpy.mean(X, axis=1)

array([2., 4.])

In [52]:
numpy.mean(X, axis=-1)

array([2., 4.])

In [65]:
X = numpy.array([1, 2, 3])
X

array([1, 2, 3])

In [66]:
X = numpy.array([[0], [1], [2]])
X

array([[0],
       [1],
       [2]])

In [70]:
X.shape

(3, 1)

In [68]:
y = numpy.array([0, 1, 2])
y

array([0, 1, 2])

In [69]:
X + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [74]:
X = numpy.array([1, 2, 3])
X

array([1, 2, 3])

In [75]:
X = numpy.array([1, 2, '3'])
X

array(['1', '2', '3'], dtype='<U11')

In [76]:
X.astype(numpy.int32)

array([1, 2, 3])

In [78]:
X = np.array([1, 2, '3'])
X

array(['1', '2', '3'], dtype='<U11')

In [79]:
X.astype(np.int64)

array([1, 2, 3], dtype=int64)

### 난수 생성 함수

In [3]:
import numpy as np

np.__version__

'1.23.4'

# random.random()
  [0.0, 1.0) 사이의 난수 생성

In [6]:
np.random.random(3)

array([0.69584745, 0.27327769, 0.36340915])

In [7]:
np.random.random(3)

array([0.73411508, 0.89840221, 0.38430211])

In [8]:
np.random.random((2, 2))

array([[0.93197113, 0.66807791],
       [0.1173746 , 0.91285058]])

In [9]:
# random, random_sample(), rand()

In [10]:
np.random.rand(3, 2)

array([[0.37417459, 0.04878934],
       [0.38834511, 0.7295111 ],
       [0.0677878 , 0.16771102]])

### 표준정규분포 추출 randn()

In [11]:
np.random.randn(3, 2)

array([[ 0.15245328,  0.80167762],
       [ 0.13177757,  1.03699232],
       [ 0.31880472, -0.8782329 ]])

### 정수 추출 randint()

In [24]:
np.random.randint(1, 45, (1,6))

array([[24, 19, 12,  5,  6, 19]])

In [25]:
np.random.randint(1, 45, (1,6))

array([[15, 31,  1, 22,  6, 28]])

In [26]:
np.random.randint(1, 45, (1,6))

array([[ 3, 10, 38, 38,  9, 43]])

In [27]:
np.random.randint(1, 45, (1,6))

array([[29, 42,  9, 29, 16, 24]])

In [28]:
np.random.randint(1, 45, (1,6))

array([[26, 30, 29,  9, 12, 36]])

In [32]:
np.random.seed(2002)
np.random.randn(3)

array([0.30098161, 0.54029727, 0.37349729])

### 연산

In [34]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

In [35]:
x + y

array([[ 6,  8],
       [10, 12]])

In [44]:
np.add(x, y), np.subtract(x, y), np.divide(x, y), np.subtract(y, x)

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]),
 array([[4, 4],
        [4, 4]]))

In [39]:
x * y, np.multiply(x, y)

(array([[ 5, 12],
        [21, 32]]),
 array([[ 5, 12],
        [21, 32]]))

In [42]:
x @ y

array([[19, 22],
       [43, 50]])

In [45]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [46]:
np.matmul(x, y)

array([[19, 22],
       [43, 50]])

In [49]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [50]:
np.matmul(x, y)

70

### np.argmax() : 생성된 난수 중 최대값의 인덱스 추출

In [58]:
x = np.random.randn(5,4)
x

array([[ 0.94979693, -0.60546144,  0.92324536, -0.33783233],
       [-0.04684576, -0.9564582 , -0.28689651, -1.64117434],
       [-2.01449175, -0.38067858,  0.84070035, -1.0659891 ],
       [ 0.39253668, -0.01708306,  0.57996853,  0.17081044],
       [ 0.25746521, -0.1747546 , -0.26220762, -1.492324  ]])

In [69]:
np.argmax(x, axis=1), np.argmax(x, axis=0)

(array([0, 0, 2, 2, 0], dtype=int64), array([0, 3, 0, 3], dtype=int64))

### 저장하기 savez()

In [70]:
x = np.random.randn(5, 4)
y = np.random.randn(3, 3)
x

array([[-0.51367482,  0.30232325, -1.68503559,  1.81021357],
       [-0.23144082, -0.48362959, -1.21067889, -1.73535342],
       [-0.92426992,  0.95416358,  1.12984836, -0.59711258],
       [-0.67519295,  2.32168905,  1.58295323, -1.54052915],
       [ 1.44616767,  0.18427423,  0.21413282, -0.87147387]])

In [71]:
y

array([[-1.25398238,  1.14069901,  0.20168216],
       [ 1.97784089,  0.00610091,  0.63417783],
       [ 0.70990048, -1.080778  ,  0.32832685]])

In [72]:
np.savez('mydata.npz', xvar=x, yvar=y)

### 모델생성

In [75]:
### 파일 로딩

mydata = np. load('mydata.npz')

In [74]:
x = mydata['xvar']
x

array([[-0.51367482,  0.30232325, -1.68503559,  1.81021357],
       [-0.23144082, -0.48362959, -1.21067889, -1.73535342],
       [-0.92426992,  0.95416358,  1.12984836, -0.59711258],
       [-0.67519295,  2.32168905,  1.58295323, -1.54052915],
       [ 1.44616767,  0.18427423,  0.21413282, -0.87147387]])

In [77]:
y = mydata['yvar']
y

array([[-1.25398238,  1.14069901,  0.20168216],
       [ 1.97784089,  0.00610091,  0.63417783],
       [ 0.70990048, -1.080778  ,  0.32832685]])